### ISSUE TITLE
option to run directly off of app/

### ISSUE THREAD

**Issue by sheppard** [wq/wq-django-template#21]
It would be handy to have a quick way to switch to running directly off of the app/ folder - after all, that capability was a key reason to use AMD modules.  Presumably this option would be triggered by `./deploy.sh` and work in both Apache and `./manage.py runserver`.

**Comment by Infernion** [comment]
+1

**Comment by sheppard** [comment]
This is working in [wq-django-template 1.3 alpha](https://github.com/wq/wq-django-template/releases/tag/v1.3.0a1)
