### ISSUE TITLE
update to django 1.8 settings template

### ISSUE THREAD

**Issue by sheppard** [wq/wq-django-template#7]
The settings.py is currently based on the 1.6 version.  Updating to 1.7 is probably a minor change but worth doing for forwards compatibility.

**Comment by auvipy** [comment]
this should be now django 1.8+

**Comment by sheppard** [comment]
Yes, it would be good to get up to the latest version.  In theory it's just a matter of generating a diff between the 1.6 default template and this one, then applying the patch to the 1.8 default template.

**Comment by auvipy** [comment]
you need help? how could I help?

**Comment by sheppard** [comment]
Sure, if you want to put a pull request together that would be great.  If you're handy with `diff` and `patch` it should be pretty straightforward - either apply the difference between Django 1.6's settings and Django 1.8's settings to the wq settings, or apply the difference between Django 1.6 settings and the wq settings to the Django 1.8 settings.  You can also just do it manually - the main differences from the default config are noted in the file.
